FROM ubuntu:22.04
ARG USER_ID

RUN dpkg --add-architecture i386
RUN apt-get update -y
RUN apt-get install -y \
	curl \
	gdb \
	wine32

RUN useradd -m -u $USER_ID user
USER user
WORKDIR /home/user
RUN mkdir -p .wine RA2
